spring:
  application:
    name: admin-service

  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
      label: main

springdoc:
  swagger-ui:
    groups-oder: DESC
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true