replicaCount: 1

image:
  repository: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/admin-service
  tag: 20250527-9997b25
  pullPolicy: IfNotPresent    # 이미지 가져오는 정책 로컬에 없을 때만 pull

service:
  type: ClusterIP   # 클러스터 내부에서만 접근 가능 (기본값)
  port: 80

# 헬스체크 설정
healthCheck:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10

# Admin Service Config 요소
config:
  server:
    port: 8080
  app:
    name: admin-service
  swagger:
    enabled: true