name: Build, Push to ECR and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  REPOSITORY_URL: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/admin-service

jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: |
          echo "IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker images for all services
        run: |
          echo "Building image for admin-service"
          docker build -t admin-service:${{ env.IMAGE_TAG }} .
          docker tag admin-service:${{ env.IMAGE_TAG }} ${{ env.REPOSITORY_URL }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REPOSITORY_URL }}:${{ env.IMAGE_TAG }}